### ISSUE TITLE
Add new feature, highlighting with ==Hightlight==

### ISSUE THREAD

**Issue by tfoerst3r** [saf-dmitry/mdviewer#15]
Maybe an addition to the viewer as discussed on [StackOverflow][stack1]. 

[stack1]: https://stackoverflow.com/questions/25104738/text-highlight-in-markdown#36039773

**Comment by tfoerst3r** [comment]
Of course people could use:

~~~
<mark>highlight</mark>
~~~

**Comment by saf-dmitry** [comment]
MDviewer does't interpret Markdown input itself relying on an external processor as described in the [manual](https://github.com/saf-dmitry/mdviewer#setting-a-markdown-processor).

While the `==highlight==` syntax becomes more and more adopted in many Markdown apps like iA Writer, Typora, or Obsidian, for the moment there is unfortunately not many command-line tools adopting it. So for the time being your best bet would probably be to stick with the `<mark>highlight</mark>` syntax or search for a Markdown processor, which can interpret the `==highlight==` syntax (probably as an extension).
