### ISSUE TITLE
Unable to get pyqtwebkit on windows

### ISSUE THREAD

**Issue by sandorex** [saf-dmitry/mdviewer#9]
I cannot install the package on windows
```
C:\Windows\system32>pip install pyqtwebkit
Collecting pyqtwebkit
  ERROR: Could not find a version that satisfies the requirement pyqtwebkit (from versions: none)
ERROR: No matching distribution found for pyqtwebkit
```

output is empty when `mdviewer.bat` ran

OS: Windows 10 x64
Version: 1809

**Comment by saf-dmitry** [comment]
Try to use the link from README <https://riverbankcomputing.com/software/pyqt/download5> to download PyQT 5.

P.S. Finding a 32-bit version of PyQT 5 could also be problematic.

**Comment by sandorex** [comment]
it seems i forgot to add any type of information about the system...

**Comment by saf-dmitry** [comment]
I think, Python, PyQT 5, and PyQtWebKit should be compliant to each other (x86_64 preferable).

P.S. Please check for typos when installing: I think it should be written as `pyqtwebkit`, not `qtpywebkit`.

**Comment by sandorex** [comment]
I even tried downloading the wheel package and installing manually but still same output

and i did try `pyqtwebkit` thats a typo
```
D:\Downloads>pip search pyqtwebkit
PyQtWebKit (5.10.1)  - Python bindings for the Qt WebKit library

D:\Downloads>pip install PyQtWebKit
Collecting PyQtWebKit
  ERROR: Could not find a version that satisfies the requirement PyQtWebKit (from versions: none)
ERROR: No matching distribution found for PyQtWebKit
```

**Comment by sandorex** [comment]
I think i figured it out... `pyqtwebkit` is available for windows x86 (32 bit) and don't think it supports  python `>=3.7`

**Comment by sandorex** [comment]
package `pyqtwebkit` is windows 32 bit only, does not work with versions higher than `3.5`

running using `python`
```
Traceback (most recent call last):
  File ".\mdviewer.py", line 15, in <module>
    VERSION = "0.4"
NameError: name 'os' is not defined
```

**Comment by sandorex** [comment]
got it working finally... [encoding](https://github.com/saf-dmitry/mdviewer/blob/7620556d80eddbdc737330b2834520a27411176c/mdviewer.py#L2) somehow makes it not find `os` module, but using 
```
# -*- coding: utf-8 -*-
``` 
seems to work fine

should i open another issue for this tho?

**Comment by saf-dmitry** [comment]
> got it working finally...

Could you, please, describe your installation procedure under MS Windows for me, step-by-step?

> should i open another issue for this tho?

Yes, please.

**Comment by sandorex** [comment]
Installation for windows (both 64 and 32 bit)

1. Install python 3.5 32 bit **(it must be 32 bit, `pyqtwebkit` doesn't support 64bit python for windows)**
2. run `cmd` as administrator and then run
```
python -m pip install --upgrade pip
python -m pip install pyyaml pyqtwebkit
```
**(note that `pyqtwebkit` will automatically install latest supported `pyqt5` as a dependency)**

downloading python 32 bit for windows can be little tricky cause it seems they do not have a windows installer for every version, latest i could find while writing this is [3.5.4](https://www.python.org/ftp/python/3.5.4/python-3.5.4.exe)

**Comment by devamanka** [comment]
if you are python any version (for 64 bit), don't tans for installing webkit. PyQT5 64 bit user use QtWebEngine and use QtWebEngineWidget. These two methods already in PyQT5 and work same like webkit ( for web browsing).
